pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    bat "cd sicei && docker build -t sicei-app-pipeline-v${env.BUILD_ID} ."
                }
            }
        }

        stage('Deploy') {
            steps {
                script {                   
                    echo 'Iniciando el contenedor...'
                     bat """
                        docker stop nest-jenkins || echo "No hay contenedor para detener"
                        docker rm nest-jenkins || echo "No hay contenedor para eliminar"
                        docker run -p 3000:3000 --name nest-jenkins -d sicei-app-pipeline:${env.BUILD_ID}
                    """
                }
            }
        }
    }
}