pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    bat "docker build -t sicei-app-pipeline-v:${env.BUILD_ID} ."
                }
            }
        }

        stage('Deploy') {
            steps {
                script {                   
                    echo 'Iniciando el contenedor...'
                    bat "docker run -p 3000:3000 --name nest -d sicei-app-pipeline-v${env.BUILD_ID}"
                }
            }
        }
    }
}